export default {
    SET_YEAR: 'SET_YEAR',
    GET_PHOTOS_REQUEST: 'GET_PHOTOS_REQUEST',
    GET_PHOTOS_SUCCESS: 'GET_PHOTOS_SUCCESS',
    GET_PHOTOS_FAIL: 'GET_PHOTOS_FAIL',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
}
